### ISSUE TITLE
Update XRD Kinds to better fit Hub/Spoke naming/architecture pattern

### ISSUE THREAD

**Issue by kurktchiev** [back-stack/architecture-decision-records#1]
Since in our architecture we are discussing the idea of a Hub+Spoke design, we should make sure that all the objects we are naming internally/externally at least have some reference to this.

Currently, the `backstage` and `crossplane` API definitions refer to objects like this:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaksclusters.backstack.dev
spec:
  group: backstack.dev
  names:
    kind: XAKSCluster
    plural: xaksclusters
  claimNames:
    kind: AKSCluster
    plural: aksclusters
```
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhubs.backstack.dev
spec:
  group: backstack.dev
  names:
    kind: XHub
    plural: xhubs
  claimNames:
    kind: Hub
    plural: hubs
```

I am proposing that instead we rename this to something more indicative of the specific purpose of the objects:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: aksclusters.spoke.backstack.dev
spec:
  group: backstack.dev
  names:
    kind: SpokeAKSCluster
    plural: spokeaksclusters
  claimNames:
    kind: AKSSpoke
    plural: aksspoke
```
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: hubs.backstack.dev
spec:
  group: backstack.dev
  names:
    kind: BackStackHub
    plural: backstackhubs
  claimNames:
    kind: Hub
    plural: hubs
```
This way things are more in line with naming conventions and ideology of the design.

cc @djeremiah @morey-tech @patelrit

**Comment by djeremiah** [comment]
This naming, while a bit more consistent with the idea of a hub/spoke for Kubernetes Provisioning, is inconsistent with Crossplane naming conventions.

XRDs must be named `<plural kind>.<group>`. Conventionally, the kind is whatever you want the Claim to be, prefixed with X (as in Composite).

So, if you want end users to interact with an object named "Hub.backstack.dev", you need to create an XRD named `xhubs.backstack.dev` with
```
names:
  kind: XHubs
  plural: xhubs
claimNames:
  kind: Hub
  plural: hubs
```
which is exactly what we have. 

I wonder if the idea of hub and spoke is a bit mis-aligned to begin with. The back stack "hub" is really just a back stack instance/deployment/platform. The "spokes" are just examples of the kinds of workloads such a platform can enable - provisioning of Kubernetes Clusters.
